FROM nvidia/cuda:10.1-base

MAINTAINER zocker-160

ENV BLENDER_MAJOR 2.79
ENV BLENDER_VERSION 2.79b
ENV BLENDER_BZ2_URL https://mirror.clarkson.edu/blender/release/Blender$BLENDER_MAJOR/blender-$BLENDER_VERSION-linux-glibc219-x86_64.tar.bz2

ENV CR_VERSION cr_025_bl279

RUN \
	apt-get update \
	&& apt-get install -y wget \
	unzip \
	tar \
	curl \
	bzip2 \
	libfreetype6 \
	libgl1-mesa-dev \
	libglu1-mesa \
	libxi6 \
	libxrender1 \
	jq \
	&& apt-get -y autoremove \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir /usr/local/blender \
	&& curl -SL "$BLENDER_BZ2_URL" -o blender.tar.bz2 \
	&& tar -jxvf blender.tar.bz2 -C /usr/local/blender --strip-components=1 \
	&& rm blender.tar.bz2


WORKDIR /CR
COPY download_cr.sh .
COPY start_cr_server_gpu.sh .
COPY install_addon.py .
COPY activate_gpu.py .

RUN chmod +x ./download_cr.sh && chmod +x ./start_cr_server_gpu.sh
RUN chmod -R 777 /CR

CMD ./start_cr_server_gpu.sh
